import React, { useState } from 'react';
import { db } from '../../services/firebase';
import { collection, addDoc, getDocs, setDoc, doc, serverTimestamp, query, where, limit } from 'firebase/firestore';
import { Button } from '../ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { AlertCircle, CheckCircle, Database, Loader2 } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';

const DatabaseSeeder: React.FC = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [result, setResult] = useState<{ type: 'success' | 'error', message: string } | null>(null);

    const seedDatabase = async () => {
        setIsLoading(true);
        setResult(null);

        try {
            const logs: string[] = [];

            // 1. Scoring Configs
            const configRef = doc(db, 'scoringConfigs', 'default');
            await setDoc(configRef, {
                weights: {
                    rating: 0.4,
                    recency: 0.2,
                    distance: 0.3,
                    niche: 0.1
                },
                thresholds: {
                    minRating: 3.5,
                    maxDistance: 5000 // meters
                },
                updatedAt: serverTimestamp()
            }, { merge: true });
            logs.push('✅ Scoring configuration initialized');

            // 2. Notifications (Test)
            const notifRef = collection(db, 'notifications');
            await addDoc(notifRef, {
                title: 'System Initialized',
                message: 'Database has been successfully seeded.',
                type: 'system',
                read: false,
                createdAt: serverTimestamp()
            });
            logs.push('✅ Test notification created');

            // 3. Security Stats (Initialize if empty)
            const statsRef = doc(db, 'securityStats', 'daily');
            await setDoc(statsRef, {
                loginAttempts: 0,
                failedLogins: 0,
                activeSessions: 0,
                blockedIps: [],
                updatedAt: serverTimestamp()
            }, { merge: true });
            logs.push('✅ Security stats initialized');

            // 4. Rate Limiting (Initialize clean slate)
            // No action needed, documents are created on demand

            // 5. Test Business Report (Optional, to verify flow)
            // Check if we have any reports first to avoid spamming
            const reportsRef = collection(db, 'businessReports');
            const q = query(reportsRef, limit(1));
            const snap = await getDocs(q);
            if (snap.empty) {
                await addDoc(reportsRef, {
                    businessId: 'test-business-id',
                    businessName: 'Test Business (Seeded)',
                    reportedBy: 'system-seeder',
                    reporterAccountType: 'anonymous',
                    reporterIpAddress: '127.0.0.1',
                    reason: 'spam_reviews',
                    description: 'This is a test report generated by the database seeder to verify the system.',
                    severity: 'low',
                    status: 'pending',
                    createdAt: serverTimestamp(),
                    updatedAt: serverTimestamp()
                });
                logs.push('✅ Test business report created');
            } else {
                logs.push('ℹ️ Reports already exist, skipping test report');
            }

            setResult({
                type: 'success',
                message: logs.join('\n')
            });

        } catch (error: any) {
            console.error('Seeding error:', error);
            setResult({
                type: 'error',
                message: `Failed to seed database: ${error.message}`
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <Database className="h-5 w-5" />
                    Database Management
                </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                <p className="text-sm text-muted-foreground">
                    Use this tool to initialize required Firestore collections and documents.
                    Safe to run multiple times (merges data).
                </p>

                <Button
                    onClick={seedDatabase}
                    disabled={isLoading}
                    className="w-full sm:w-auto"
                >
                    {isLoading ? (
                        <>
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            Seeding...
                        </>
                    ) : (
                        'Seed Database'
                    )}
                </Button>

                {result && (
                    <Alert variant={result.type === 'error' ? 'destructive' : 'default'} className={result.type === 'success' ? 'border-green-500 text-green-700 bg-green-50' : ''}>
                        {result.type === 'error' ? <AlertCircle className="h-4 w-4" /> : <CheckCircle className="h-4 w-4" />}
                        <AlertTitle>{result.type === 'error' ? 'Error' : 'Success'}</AlertTitle>
                        <AlertDescription className="whitespace-pre-line mt-2">
                            {result.message}
                        </AlertDescription>
                    </Alert>
                )}
            </CardContent>
        </Card>
    );
};

export default DatabaseSeeder;
